/**
 * Source Adapter Framework Types (W34)
 *
 * Defines the canonical IngestItem envelope and adapter interface
 * that all source adapters must implement.
 */

export interface IngestItem {
  /** Unique ID for this item (generated by adapter or caller) */
  id: string;
  /** Source adapter identifier (e.g. 'telegram', 'http', 'file-watcher', 'obsidian') */
  source: string;
  /** Content type hint for downstream processing */
  contentType: 'text' | 'voice' | 'document' | 'link' | 'markdown' | 'transcript' | 'meeting';
  /** The raw content body */
  content: string;
  /** Optional binary/media URL for non-text items */
  mediaUrl?: string;
  /** Sender/author identification */
  sender: {
    id: string;
    name: string;
    handle?: string;
  };
  /** Conversation or channel context */
  channel: {
    id: string;
    name?: string;
    platform: string;
  };
  /** SHA-256 hash of content for deduplication */
  contentHash: string;
  /** ISO timestamp of when the item was originally created */
  originTimestamp: string;
  /** Arbitrary metadata from the source */
  metadata?: Record<string, unknown>;
}

export interface SourceAdapter {
  /** Unique name for this adapter */
  readonly name: string;
  /** Convert source-specific data into an IngestItem */
  toIngestItem(raw: unknown): IngestItem | null;
}

export interface IngestResult {
  accepted: boolean;
  itemId: string;
  duplicate: boolean;
  reason?: string;
}
