/**
 * Obsidian Markdown Templates (W40)
 *
 * Templates for generating Obsidian-compatible markdown files
 * from Mnemo entities, insights, and briefings.
 */

export interface EntityTemplateData {
  name: string;
  type: string;
  description?: string;
  facts: Array<{ predicate: string; object: string }>;
  relatedEntities: Array<{ name: string; relationship: string }>;
  lastUpdated: string;
}

export interface InsightTemplateData {
  title: string;
  body: string;
  type: string;
  entities: string[];
  confidence: number;
  generatedAt: string;
}

export interface BriefingTemplateData {
  date: string;
  summary: string;
  sections: Array<{ title: string; content: string }>;
}

export function renderEntityNote(data: EntityTemplateData): string {
  const lines: string[] = [
    '---',
    `title: "${data.name}"`,
    `type: ${data.type}`,
    `source: mnemo`,
    `updated: ${data.lastUpdated}`,
    '---',
    '',
    `# ${data.name}`,
    '',
  ];

  if (data.description) {
    lines.push(data.description, '');
  }

  if (data.facts.length > 0) {
    lines.push('## Facts', '');
    for (const fact of data.facts) {
      lines.push(`- **${fact.predicate}**: ${fact.object}`);
    }
    lines.push('');
  }

  if (data.relatedEntities.length > 0) {
    lines.push('## Related', '');
    for (const rel of data.relatedEntities) {
      lines.push(`- [[${rel.name}]] (${rel.relationship})`);
    }
    lines.push('');
  }

  lines.push('---', '*Generated by Mnemo*', '');
  return lines.join('\n');
}

export function renderInsightNote(data: InsightTemplateData): string {
  const lines: string[] = [
    '---',
    `title: "${data.title}"`,
    `type: insight-${data.type}`,
    `source: mnemo`,
    `confidence: ${data.confidence}`,
    `generated: ${data.generatedAt}`,
    `tags: [mnemo-insight]`,
    '---',
    '',
    `# ${data.title}`,
    '',
    data.body,
    '',
  ];

  if (data.entities.length > 0) {
    lines.push('## Related Entities', '');
    for (const entity of data.entities) {
      lines.push(`- [[${entity}]]`);
    }
    lines.push('');
  }

  lines.push('---', '*Generated by Mnemo*', '');
  return lines.join('\n');
}

export function renderBriefingNote(data: BriefingTemplateData): string {
  const lines: string[] = [
    '---',
    `title: "Briefing ${data.date}"`,
    `type: briefing`,
    `source: mnemo`,
    `date: ${data.date}`,
    `tags: [mnemo-briefing]`,
    '---',
    '',
    `# Morning Briefing — ${data.date}`,
    '',
    data.summary,
    '',
  ];

  for (const section of data.sections) {
    lines.push(`## ${section.title}`, '', section.content, '');
  }

  lines.push('---', '*Generated by Mnemo*', '');
  return lines.join('\n');
}
