// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://src` | (string & {});
};

/**
 * BatchEmbedRequest
 *
 * Request body for batch embedding
 */
export type BatchEmbedRequest = {
    /**
     * Texts
     */
    texts: Array<string>;
    /**
     * Model
     */
    model?: string;
};

/**
 * BatchEmbedResponse
 *
 * Response body with multiple embeddings
 */
export type BatchEmbedResponse = {
    /**
     * Embeddings
     */
    embeddings: Array<Array<number>>;
    /**
     * Model
     */
    model: string;
    /**
     * Dimensions
     */
    dimensions: number;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_transcribe_upload_transcribe_upload_post
 */
export type BodyTranscribeUploadTranscribeUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CheckContradictionRequest
 */
export type CheckContradictionRequest = {
    fact1: FactData;
    fact2: FactData;
};

/**
 * CheckContradictionResponse
 */
export type CheckContradictionResponse = {
    /**
     * Contradicts
     */
    contradicts: boolean;
    /**
     * Type
     */
    type: string;
    /**
     * Resolution
     */
    resolution: string;
    /**
     * Reasoning
     */
    reasoning: string;
    /**
     * Confidence
     */
    confidence: number;
};

/**
 * ClassifyRequest
 *
 * Request body for classification
 */
export type ClassifyRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Include Reasoning
     */
    include_reasoning?: boolean;
};

/**
 * ClassifyResponse
 *
 * Classification result
 */
export type ClassifyResponse = {
    /**
     * Intents
     */
    intents: Array<Intent>;
    /**
     * Primary Intent
     */
    primary_intent: string;
    /**
     * Suggested Workflow
     */
    suggested_workflow: string;
    /**
     * Reasoning
     */
    reasoning?: string | null;
};

/**
 * EmbedRequest
 *
 * Request body for embedding generation
 */
export type EmbedRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Model
     */
    model?: string;
};

/**
 * EmbedResponse
 *
 * Response body with embedding vector
 */
export type EmbedResponse = {
    /**
     * Vector
     */
    vector: Array<number>;
    /**
     * Model
     */
    model: string;
    /**
     * Dimensions
     */
    dimensions: number;
};

/**
 * EntityMention
 */
export type EntityMention = {
    /**
     * Mention
     */
    mention: string;
    /**
     * Type
     */
    type: string;
    /**
     * Properties
     */
    properties?: {
        [key: string]: unknown;
    };
    /**
     * Start
     */
    start?: number;
    /**
     * End
     */
    end?: number;
    /**
     * Confidence
     */
    confidence?: number;
};

/**
 * ExtractEntitiesRequest
 */
export type ExtractEntitiesRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Include Context
     */
    include_context?: boolean;
};

/**
 * ExtractEntitiesResponse
 */
export type ExtractEntitiesResponse = {
    /**
     * Entities
     */
    entities: Array<EntityMention>;
    /**
     * Text Length
     */
    text_length: number;
};

/**
 * ExtractRelationshipsRequest
 */
export type ExtractRelationshipsRequest = {
    /**
     * Content
     */
    content: string;
    /**
     * Entities
     */
    entities?: Array<ExtractedEntity>;
};

/**
 * ExtractRelationshipsResponse
 */
export type ExtractRelationshipsResponse = {
    /**
     * Relationships
     */
    relationships: Array<Relationship>;
    /**
     * Source Content Hash
     */
    source_content_hash: string;
};

/**
 * ExtractTaskRequest
 *
 * Request body for task extraction
 */
export type ExtractTaskRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * ExtractTaskResponse
 *
 * Extracted task details
 */
export type ExtractTaskResponse = {
    /**
     * Action
     */
    action: string;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Confidence
     */
    confidence?: number;
    /**
     * Raw Due Text
     */
    raw_due_text?: string | null;
};

/**
 * ExtractedEntity
 */
export type ExtractedEntity = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type?: string | null;
};

/**
 * FactData
 */
export type FactData = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Predicate
     */
    predicate: string;
    /**
     * Object
     */
    object: string;
    /**
     * Valid At
     */
    valid_at?: string | null;
    /**
     * Invalid At
     */
    invalid_at?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Intent
 *
 * Single intent with confidence
 */
export type Intent = {
    /**
     * Type
     */
    type: string;
    /**
     * Confidence
     */
    confidence: number;
};

/**
 * ParseContentRequest
 */
export type ParseContentRequest = {
    /**
     * Content
     */
    content: string;
    /**
     * Hint
     */
    hint?: string | null;
};

/**
 * ParseContentResponse
 */
export type ParseContentResponse = {
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Mentions
     */
    mentions: Array<string>;
    /**
     * Dates
     */
    dates: Array<string>;
    /**
     * Links
     */
    links: Array<string>;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Sentiment
     */
    sentiment: string;
    /**
     * Language
     */
    language: string;
    /**
     * Word Count
     */
    word_count: number;
};

/**
 * Relationship
 */
export type Relationship = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Predicate
     */
    predicate: string;
    /**
     * Object
     */
    object: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Temporal Hint
     */
    temporal_hint?: string;
    /**
     * Source Text
     */
    source_text?: string | null;
};

/**
 * ResolveEntityRequest
 */
export type ResolveEntityRequest = {
    /**
     * New Mention
     */
    new_mention: string;
    /**
     * Context
     */
    context: string;
    /**
     * Existing Entity
     */
    existing_entity: {
        [key: string]: unknown;
    };
};

/**
 * ResolveEntityResponse
 */
export type ResolveEntityResponse = {
    /**
     * Decision
     */
    decision: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Reasoning
     */
    reasoning: string;
};

/**
 * ScrapeRequest
 *
 * Request body for scraping
 */
export type ScrapeRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * ScrapeResponse
 *
 * Scraped content response
 */
export type ScrapeResponse = {
    /**
     * Url
     */
    url: string;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Text
     */
    text: string;
    /**
     * Domain
     */
    domain: string;
    /**
     * Word Count
     */
    word_count: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Image
     */
    image?: string | null;
};

/**
 * SummarizeRequest
 *
 * Request body for summarization
 */
export type SummarizeRequest = {
    /**
     * Content
     */
    content: string;
    /**
     * Title
     */
    title?: string;
};

/**
 * SummarizeResponse
 *
 * Summarization result
 */
export type SummarizeResponse = {
    /**
     * Summary
     */
    summary: string;
    /**
     * Key Points
     */
    key_points: Array<string>;
    /**
     * Word Count
     */
    word_count: number;
};

/**
 * TranscribeResponse
 *
 * Response body with transcription
 */
export type TranscribeResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Language
     */
    language: string;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Segments
     */
    segments?: Array<unknown> | null;
};

/**
 * TranscribeUrlRequest
 *
 * Request body for URL-based transcription
 */
export type TranscribeUrlRequest = {
    /**
     * Audio Url
     */
    audio_url: string;
    /**
     * Language
     */
    language?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type EmbedEmbedPostData = {
    body: EmbedRequest;
    path?: never;
    query?: never;
    url: '/embed';
};

export type EmbedEmbedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EmbedEmbedPostError = EmbedEmbedPostErrors[keyof EmbedEmbedPostErrors];

export type EmbedEmbedPostResponses = {
    /**
     * Successful Response
     */
    200: EmbedResponse;
};

export type EmbedEmbedPostResponse = EmbedEmbedPostResponses[keyof EmbedEmbedPostResponses];

export type EmbedBatchEmbedBatchPostData = {
    body: BatchEmbedRequest;
    path?: never;
    query?: never;
    url: '/embed/batch';
};

export type EmbedBatchEmbedBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EmbedBatchEmbedBatchPostError = EmbedBatchEmbedBatchPostErrors[keyof EmbedBatchEmbedBatchPostErrors];

export type EmbedBatchEmbedBatchPostResponses = {
    /**
     * Successful Response
     */
    200: BatchEmbedResponse;
};

export type EmbedBatchEmbedBatchPostResponse = EmbedBatchEmbedBatchPostResponses[keyof EmbedBatchEmbedBatchPostResponses];

export type ListModelsEmbedModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/embed/models';
};

export type ListModelsEmbedModelsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranscribeStatusTranscribeStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/transcribe/status';
};

export type TranscribeStatusTranscribeStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranscribeUrlTranscribePostData = {
    body: TranscribeUrlRequest;
    path?: never;
    query?: never;
    url: '/transcribe';
};

export type TranscribeUrlTranscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeUrlTranscribePostError = TranscribeUrlTranscribePostErrors[keyof TranscribeUrlTranscribePostErrors];

export type TranscribeUrlTranscribePostResponses = {
    /**
     * Successful Response
     */
    200: TranscribeResponse;
};

export type TranscribeUrlTranscribePostResponse = TranscribeUrlTranscribePostResponses[keyof TranscribeUrlTranscribePostResponses];

export type TranscribeUploadTranscribeUploadPostData = {
    body: BodyTranscribeUploadTranscribeUploadPost;
    path?: never;
    query?: never;
    url: '/transcribe/upload';
};

export type TranscribeUploadTranscribeUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeUploadTranscribeUploadPostError = TranscribeUploadTranscribeUploadPostErrors[keyof TranscribeUploadTranscribeUploadPostErrors];

export type TranscribeUploadTranscribeUploadPostResponses = {
    /**
     * Successful Response
     */
    200: TranscribeResponse;
};

export type TranscribeUploadTranscribeUploadPostResponse = TranscribeUploadTranscribeUploadPostResponses[keyof TranscribeUploadTranscribeUploadPostResponses];

export type ClassifyMessageClassifyPostData = {
    body: ClassifyRequest;
    path?: never;
    query?: never;
    url: '/classify';
};

export type ClassifyMessageClassifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClassifyMessageClassifyPostError = ClassifyMessageClassifyPostErrors[keyof ClassifyMessageClassifyPostErrors];

export type ClassifyMessageClassifyPostResponses = {
    /**
     * Successful Response
     */
    200: ClassifyResponse;
};

export type ClassifyMessageClassifyPostResponse = ClassifyMessageClassifyPostResponses[keyof ClassifyMessageClassifyPostResponses];

export type TestClassificationClassifyTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/classify/test';
};

export type TestClassificationClassifyTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScrapeUrlScrapePostData = {
    body: ScrapeRequest;
    path?: never;
    query?: never;
    url: '/scrape';
};

export type ScrapeUrlScrapePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScrapeUrlScrapePostError = ScrapeUrlScrapePostErrors[keyof ScrapeUrlScrapePostErrors];

export type ScrapeUrlScrapePostResponses = {
    /**
     * Successful Response
     */
    200: ScrapeResponse;
};

export type ScrapeUrlScrapePostResponse = ScrapeUrlScrapePostResponses[keyof ScrapeUrlScrapePostResponses];

export type TestScrapeScrapeTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scrape/test';
};

export type TestScrapeScrapeTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SummarizeContentSummarizePostData = {
    body: SummarizeRequest;
    path?: never;
    query?: never;
    url: '/summarize';
};

export type SummarizeContentSummarizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SummarizeContentSummarizePostError = SummarizeContentSummarizePostErrors[keyof SummarizeContentSummarizePostErrors];

export type SummarizeContentSummarizePostResponses = {
    /**
     * Successful Response
     */
    200: SummarizeResponse;
};

export type SummarizeContentSummarizePostResponse = SummarizeContentSummarizePostResponses[keyof SummarizeContentSummarizePostResponses];

export type TestSummarizeSummarizeTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/summarize/test';
};

export type TestSummarizeSummarizeTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExtractTaskExtractTaskPostData = {
    body: ExtractTaskRequest;
    path?: never;
    query?: never;
    url: '/extract-task';
};

export type ExtractTaskExtractTaskPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractTaskExtractTaskPostError = ExtractTaskExtractTaskPostErrors[keyof ExtractTaskExtractTaskPostErrors];

export type ExtractTaskExtractTaskPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractTaskResponse;
};

export type ExtractTaskExtractTaskPostResponse = ExtractTaskExtractTaskPostResponses[keyof ExtractTaskExtractTaskPostResponses];

export type TestTaskExtractionExtractTaskTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/extract-task/test';
};

export type TestTaskExtractionExtractTaskTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExtractEntitiesExtractEntitiesPostData = {
    body: ExtractEntitiesRequest;
    path?: never;
    query?: never;
    url: '/extract-entities';
};

export type ExtractEntitiesExtractEntitiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractEntitiesExtractEntitiesPostError = ExtractEntitiesExtractEntitiesPostErrors[keyof ExtractEntitiesExtractEntitiesPostErrors];

export type ExtractEntitiesExtractEntitiesPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractEntitiesResponse;
};

export type ExtractEntitiesExtractEntitiesPostResponse = ExtractEntitiesExtractEntitiesPostResponses[keyof ExtractEntitiesExtractEntitiesPostResponses];

export type ResolveEntityResolveEntityPostData = {
    body: ResolveEntityRequest;
    path?: never;
    query?: never;
    url: '/resolve-entity';
};

export type ResolveEntityResolveEntityPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveEntityResolveEntityPostError = ResolveEntityResolveEntityPostErrors[keyof ResolveEntityResolveEntityPostErrors];

export type ResolveEntityResolveEntityPostResponses = {
    /**
     * Successful Response
     */
    200: ResolveEntityResponse;
};

export type ResolveEntityResolveEntityPostResponse = ResolveEntityResolveEntityPostResponses[keyof ResolveEntityResolveEntityPostResponses];

export type TestExtractionExtractEntitiesTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/extract-entities/test';
};

export type TestExtractionExtractEntitiesTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckContradictionCheckContradictionPostData = {
    body: CheckContradictionRequest;
    path?: never;
    query?: never;
    url: '/check-contradiction';
};

export type CheckContradictionCheckContradictionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckContradictionCheckContradictionPostError = CheckContradictionCheckContradictionPostErrors[keyof CheckContradictionCheckContradictionPostErrors];

export type CheckContradictionCheckContradictionPostResponses = {
    /**
     * Successful Response
     */
    200: CheckContradictionResponse;
};

export type CheckContradictionCheckContradictionPostResponse = CheckContradictionCheckContradictionPostResponses[keyof CheckContradictionCheckContradictionPostResponses];

export type TestContradictionCheckContradictionTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/check-contradiction/test';
};

export type TestContradictionCheckContradictionTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ParseContentParseContentPostData = {
    body: ParseContentRequest;
    path?: never;
    query?: never;
    url: '/parse-content';
};

export type ParseContentParseContentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseContentParseContentPostError = ParseContentParseContentPostErrors[keyof ParseContentParseContentPostErrors];

export type ParseContentParseContentPostResponses = {
    /**
     * Successful Response
     */
    200: ParseContentResponse;
};

export type ParseContentParseContentPostResponse = ParseContentParseContentPostResponses[keyof ParseContentParseContentPostResponses];

export type TestParseParseContentTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parse-content/test';
};

export type TestParseParseContentTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExtractRelationshipsExtractRelationshipsPostData = {
    body: ExtractRelationshipsRequest;
    path?: never;
    query?: never;
    url: '/extract-relationships';
};

export type ExtractRelationshipsExtractRelationshipsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractRelationshipsExtractRelationshipsPostError = ExtractRelationshipsExtractRelationshipsPostErrors[keyof ExtractRelationshipsExtractRelationshipsPostErrors];

export type ExtractRelationshipsExtractRelationshipsPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractRelationshipsResponse;
};

export type ExtractRelationshipsExtractRelationshipsPostResponse = ExtractRelationshipsExtractRelationshipsPostResponses[keyof ExtractRelationshipsExtractRelationshipsPostResponses];

export type TestRelationshipsExtractRelationshipsTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/extract-relationships/test';
};

export type TestRelationshipsExtractRelationshipsTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
